### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by egydesen** [particle-iot/particle-api-js#101]
If including https://cdn.jsdelivr.net/particle-api-js/5/particle.min.js on a site that already has executed "require('babel-polyfill');", the script won't load and the API is not available. 
The issue has been raised over at babel a few times (e.g. https://github.com/babel/babel/issues/4019), but the issue seems to still exist. 

A quick solution would likely be to do 
if (! window._babelPolyfill) {
  require("babel-polyfill");
}
in Particle.js to avoid requiring babel twice.

**Comment by monkbroc** [comment]
This is already fixed in a later version. See https://github.com/particle-iot/particle-api-js/blob/master/README.md#jsdelivr-cdn for instructions on how to include the later version through cdnjs
