### ISSUE TITLE
downloadFirmwareBinary and downloadProductFirmware don't check this.prefix

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-api-js#110]
it appears both of these calls are probably broken, they use this.prefix (most other calls use this in request builder which checks to see if it's defined).  Bringing the check from build request to those calls to fix the download functions.

**Comment by busticated** [comment]
yeah, ran into this yesterday 🤦‍♂ 

https://app.clubhouse.io/particle/story/45862/downloadproductfirmware-and-downloadfirmwarebinary-fail-w-typeerror-fn-is-not-a-function
