### ISSUE TITLE
listProductFirmware returns "response" instead of parsed response

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-api-js#113]
was expecting the promise to return:

[ fw_1, fw_2, ... etc]

instead promise returns:
{ statusCode: 200, body: [fw_1, fw_2, ... etc] }

whichever we use, we should document it

**Comment by busticated** [comment]
> was expecting the promise to return
> [ fw_1, fw_2, ... etc]

best i can tell pretty much all `GET` and `HEAD` requests return a basic response object (e.g. `{ { statusCode, body }`

> whichever we use, we should document it

lol another one i logged a few days back 🤝 

https://app.clubhouse.io/particle/story/45778/improve-jsdoc-data

...if you have specific requests, feel free to add them to that story.

but, yes, we definitely need to do better across the board. thanks for the report  :pray::+1:
