### ISSUE TITLE
Particle.CallFunction Not Working

### ISSUE THREAD

**Issue by kshahzada** [particle-iot/particle-api-js#125]
I've tried to use particle.function
```    const fnPr = particle.callFunction({ deviceId, name: 'syncDis', argument: count, auth: token });```
And it keeps returning 404, function not found. I know this is wrong because I can use this exact same function with the Console, Postman, and have resorted to an Axios request to the API. I think something in the wrapper must be messed up.

I'm in a bit of a rush (making a Christmas gift for my mom) so I'm just using the API and it works but it'd be nice to get this fixed.

Functioning work around
```
const callParticleFunction = ({deviceId, name, argument, auth}) => {
    var axios = require('axios');
    var qs = require('qs');
    var data = qs.stringify({
        'arg': ''+argument 
    });
    var config = {
    method: 'post',
    url: `https://api.particle.io/v1/devices/${deviceId}/${name}`,
    headers: { 
        'Authorization': `Bearer ${auth}`, 
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    data : data
    };
    return axios(config)
}
```

**Comment by busticated** [comment]
i just tried over here and i'm able to call functions without issue using `v9.1.0` (latest at the time of writing this). one thing to double-check is that you are passing in a `string` for the `argument` option 👍

**Comment by kshahzada** [comment]
I first tried it with count as a string but I'll go double-check

**Comment by kshahzada** [comment]
Yup - definitely was the problem 🤦🏻‍♂️
