### ISSUE TITLE
SSE event stream ends without 'end' event being triggered

### ISSUE THREAD

**Issue by opyh** [particle-iot/particle-api-js#15]
I currently have the problem that my particle events stream socket seems to be closed after a while without any notification if no events are happening.

I use an implementation similar to this one:
https://github.com/spark/sparkjs/blob/master/examples/node/get-event-stream-forever.js

New events will just not be sent to the client. Meanwhile, the client's 'end' event is not triggered, so there is currently no way for the client to know and no reconnection happens. This can be an issue with a user's network infrastructure, too. I need to find a way to ensure the channel still works after keeping it open for a longer while.

Is there already heartbeat/keepalive mechanism that allows the client to find out if the connection is still open? Or do I have to send events from my node client periodically to keep the subscription channel open and find out if I have to reconnect?

**Comment by brycekahle** [comment]
Since 5.1.0 the event stream should reconnect automatically. If it cannot, it will throw an `error` event. Some example code is below:

```
api.getEventStream({ deviceId: 'aaa', auth: '111' }).then(function (req) {
  req.on('event', function(e) {
    console.log(e);
  });
  req.on('error', function(err) {
    console.log(err);
    // trigger full reconnection here
  });
}, function(err) {
  // initial connection error
});
```

Does this help?

**Comment by alxlo** [comment]
Nope, this does not seem to work. When a disconnect occurs, neither reconnection is triggered nor is there any error event emitted.

**Comment by SleepyTonic** [comment]
I tracked this down and the problem surfaces when the events stream contains a extra newline character.

I went to https://api.particle.io/v1/events?access_token=[token] and collected the public sample below:
>...
> event: DoorMsg
> data: {"data":"Door closing or opening","ttl":"60","published_at":"2017-01-27T21:51:28.335Z","coreid":"51ff6e065082554906370887"}
> 
> event: Motion
> data: {"data":"2","ttl":"60","published_at":"2017-01-27T21:51:29.392Z","coreid":"35003d000447343337373738"}
> 
> event: 15.734930C, 41.187805%, 29.667389in.Hg
> 
> data: {"data":"null","ttl":"60","published_at":"2017-01-27T21:51:28.262Z","coreid":"370036000547343233323032"}
> ...
> 

The module throws a squashed SyntaxException at EventStream.parseEventStreamLine after the event "event: 15.734930C, 41.187805%, 29.667389in.Hg" is parsed and doesn't recover.

**Comment by alxlo** [comment]
This might be a separate problem. IMHO we have here:
- event stream parsing fails due to improper handling of newlines in payload
- event stream interruption/disconnection is not handled as expected and is not signaled to listeners

**Comment by adkinsjd** [comment]
Has any progress been made on this issue? After several hours I stop getting events from a getEventStream listener and I am not receiving any 'end' or 'error' events indicating that I should restart the stream. Interestingly, another getEventStream listener that is running in the same process but listening for different events continues working as expected.  

I have resorted to restarting the stream periodically, however that's not a very principled solution given that I don't know what's causing the disconnection in the first place.

**Comment by alikrubin** [comment]
I have the exact same problem.

**Comment by rlaurente** [comment]
when will this issue get solve ? any workarounds ?

Thanks

**Comment by monkbroc** [comment]
@rlaurente it's possible your event handler is throwing an exception and crashing the event processing loop.

Add a `try {} catch` inside your event handler:
```
  stream.on('event', event => {
	try {
	  console.log(`received event`, event);
	  crash;
	} catch (error) {
	  console.error('crash in event handler', error);
	}
  });
```
