### ISSUE TITLE
Add configurable User-Agent

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-api-js#18]
Currently particle-api-js sends `User-Agent: node-superagent/1.8.3`

The default should be `particle-api-js/${version}`. For different applications it would be useful to be able to set this value.

**Comment by brycekahle** [comment]
See #10

**Comment by monkbroc** [comment]
Thanks for the link. Making the user agent configurable with a default for node.js usage would be useful since we want to use particle-api-js in the CLI and Dev.
