### ISSUE TITLE
particle.listDevices is not working

### ISSUE THREAD

**Issue by callen5914** [particle-iot/particle-api-js#49]
'use strict'

const Particle = require('particle-api-js')
const particle = new Particle();

class DeviceController {
    \* index(request, response){

```
    const token = request.cookie('token')

    const devicesPr = yield particle.listDevices({ auth: token })

    devicesPr.then(
        function(devices){
            console.log('Devices: ', devices);
        },
        function(err) {
            console.log('List devices call failed: ', err);
        }
    );

    yield response.sendView('devices', {devices: devicesPr})

    console.log(devicesPr)
}
```

}

module.exports = DeviceController

---

This is returning that devicesPr is not a function

**Comment by monkbroc** [comment]
I've never tried using this library with a generator and I'm not familiar enough with the syntax.

Can you try with plain Promises?

```
const Particle = require('particle-api-js')
const particle = new Particle();
particle.listDevices({ auth: token }).then(console.log, console.error);
```

**Comment by theworkflow** [comment]
Hey @callen5914 thanks for submitting this issue. I'm going to close this issue since it's from a few years back. If you still feel this is something we need to address please open another issue with more details. Thanks for being part of the Particle community 😄
