### ISSUE TITLE
getEventStream register all events high cpu load

### ISSUE THREAD

**Issue by brettdaman** [particle-iot/particle-api-js#65]
Today I noticed a very weird problem where my servers cpu was maxed out when I added the particle event stream listener.

A device is sending every 10seconds a notification on an eventstream named 'test' and my cpu goes higher every time the device sends. After 4 or 5 messages it reaches 100% and everything stops working.

code is copied from the documentation  https://docs.particle.io/reference/javascript/#get-event-stream

//Get all events
particle.getEventStream({ auth: token}).then(function(stream) {

If I change the code to listen on only one named event stream everything works fine.

//Get test events
particle.getEventStream({ auth: token, name: 'test'}).then(function(stream) {

Does anyone have an idea or a possible solution to support all events without blocking?

**Comment by monkbroc** [comment]
To listen to events from your devices only, use `particle.getEventStream({ deviceId: 'mine', auth: token}).then(function(stream) {`. Otherwise you get public events published by other devices too.
