### ISSUE TITLE
Version 7.1.0 not published to npm

### ISSUE THREAD

**Issue by jwarning** [particle-iot/particle-api-js#82]
As far as I can tell version 7.1.0 has not been published to the npm registry yet, as 7.0.1 is still listed as the latest version there. Would it please be possible to publish the updated version?

**Comment by monkbroc** [comment]
I'll take a look. It's supposed to auto-publish to npm so I'll go fix that.

**Comment by monkbroc** [comment]
Done. I published 7.1.1 to npm
